### ISSUE TITLE
zmq::poll: Socket operation on non-socket

### ISSUE THREAD

**Issue by zwb-ict** [erickt/rust-zmq#189]
I use crate **nix** to create pipe, then create socket use **pipe.0's addr** as **zmq::Socket::from_raw**'s param, at runtime get error: **zmq::poll: Socket operation on non-socket** 

Anything wrong with my program?

``` rust 
extern crate nix;
extern crate zmq;

use std::io::{self, Write};
use std::os::raw::c_void;
use std::os::unix::io::RawFd;
use std::process;
use nix::sys::signal;

static mut S_FD: RawFd = -1;

extern "C" fn s_signal_handler(_: i32) {
    unsafe {
        let rc = nix::unistd::write(S_FD, b" ");
        match rc {
            Ok(_) => {}
            Err(_) => {
                println!("Error while writing to self-pipe.");
                let _ = io::stdout().flush();
            }
        }
    }
}

fn s_catch_signals(fd: RawFd) {
    unsafe {
        S_FD = fd;
    }

    let sig_action = signal::SigAction::new(signal::SigHandler::Handler(s_signal_handler),
                                            signal::SaFlags::empty(),
                                            signal::SigSet::empty());
    unsafe {
        signal::sigaction(signal::SIGINT, &sig_action).unwrap();
        signal::sigaction(signal::SIGTERM, &sig_action).unwrap();
    }
}

fn main() {
    let context = zmq::Context::new();
    let socket = context.socket(zmq::REP).unwrap();
    assert!(socket.bind("tcp://*:5555").is_ok());

    let mut pipefds = nix::unistd::pipe().unwrap();
    nix::fcntl::fcntl(pipefds.0, nix::fcntl::F_GETFL).unwrap();
    nix::fcntl::fcntl(pipefds.0, nix::fcntl::F_SETFL(nix::fcntl::O_NONBLOCK)).unwrap();

    let pipefds0_ptr: *mut RawFd = &mut pipefds.0;
    let pipefds0 = unsafe { zmq::Socket::from_raw(pipefds0_ptr as *mut c_void) };

    s_catch_signals(pipefds.1);

    let items = &mut [pipefds0.as_poll_item(zmq::POLLIN),
                      socket.as_poll_item(zmq::POLLIN)];

    loop {
        let rc = zmq::poll(items, -1);
        match rc {
            Ok(v) => {
                assert!(v >= 0);
                if v == 0 {
                    continue;
                }
                if items[0].is_readable() {
                    let buffer = &mut [0; 1];
                    nix::unistd::read(pipefds.0, buffer).unwrap();
                    println!("W: interrupt received, killing server...");
                    break;
                }
                if items[1].is_readable() {
                    let buffer = &mut [0; 255];
                    let rc = socket.recv_into(buffer, zmq::DONTWAIT);
                    match rc {
                        Ok(_) => println!("W: recv"),
                        Err(e) => {
                            if e == zmq::Error::EAGAIN || e == zmq::Error::EINTR {
                                continue;
                            }
                            println!("recv: {}", e);
                            process::exit(1);
                        }
                    }
                }
            }
            Err(e) => {
                if e == zmq::Error::EINTR {
                    continue;
                }
                println!("zmq::poll: {}", e);
                process::exit(1);
            }
        }
    }
}
```

**Comment by birkenfeld** [comment]
Don't make a socket out of a raw fd that isn't a socket. Rather, use `PollItem::from_fd()` to get a poll item.

**Comment by zwb-ict** [comment]
Thank you @birkenfeld, this issue solved. There's another issue, at runtime I run CTRL+C, get panic:
> ^Cthread 'main' panicked at 'unknown error [4]: Interrupted system call', /home/zwb/.cargo/registry/src/github.com-1ecc6299db9ec823/zmq-0.8.1/src/lib.rs:307

with ```RUST_BACKTRACE=1 target/release/interrupt``` get:

> stack backtrace:
>    0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
>              at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
>    1: std::sys_common::backtrace::_print
>              at /checkout/src/libstd/sys_common/backtrace.rs:71
>    2: std::panicking::default_hook::{{closure}}
>              at /checkout/src/libstd/sys_common/backtrace.rs:60
>              at /checkout/src/libstd/panicking.rs:355
>    3: std::panicking::default_hook
>              at /checkout/src/libstd/panicking.rs:371
>    4: std::panicking::rust_panic_with_hook
>              at /checkout/src/libstd/panicking.rs:549
>    5: std::panicking::begin_panic
>              at /checkout/src/libstd/panicking.rs:511
>    6: std::panicking::begin_panic_fmt
>              at /checkout/src/libstd/panicking.rs:495
>    7: zmq::Error::from_raw
>    8: zmq::poll
>    9: interrupt::main
>   10: __rust_maybe_catch_panic
>              at /checkout/src/libpanic_unwind/lib.rs:98
>   11: std::rt::lang_start
>              at /checkout/src/libstd/panicking.rs:433
>              at /checkout/src/libstd/panic.rs:361
>              at /checkout/src/libstd/rt.rs:59
>   12: __libc_start_main
>   13: _start

the new code:

``` rust
extern crate nix;
extern crate zmq;

use std::io::{self, Write};
// use std::os::raw::c_void;
use std::os::unix::io::RawFd;
use std::process;
use nix::sys::signal;

static mut S_FD: RawFd = -1;

extern "C" fn s_signal_handler(_: i32) {
    let rc = unsafe { nix::unistd::write(S_FD, b" ") };
    match rc {
        Ok(_) => {}
        Err(_) => {
            println!("Error while writing to self-pipe.");
            let _ = io::stdout().flush();
        }
    }
}

fn s_catch_signals(fd: RawFd) {
    unsafe {
        S_FD = fd;
    }

    let sig_action = signal::SigAction::new(signal::SigHandler::Handler(s_signal_handler),
                                            signal::SaFlags::empty(),
                                            signal::SigSet::empty());
    unsafe {
        signal::sigaction(signal::SIGINT, &sig_action).unwrap();
        signal::sigaction(signal::SIGTERM, &sig_action).unwrap();
    }
}

fn main() {
    let context = zmq::Context::new();
    let socket = context.socket(zmq::REP).unwrap();
    assert!(socket.bind("tcp://*:5555").is_ok());

    let pipefds = nix::unistd::pipe().unwrap();
    nix::fcntl::fcntl(pipefds.0, nix::fcntl::F_GETFL).unwrap();
    nix::fcntl::fcntl(pipefds.0, nix::fcntl::F_SETFL(nix::fcntl::O_NONBLOCK)).unwrap();

    // let pipefds0_ptr: *mut RawFd = &mut pipefds.0;
    // let pipefds0 = unsafe { zmq::Socket::from_raw(pipefds0_ptr as *mut c_void) };

    s_catch_signals(pipefds.1);

    // let items = &mut [pipefds0.as_poll_item(zmq::POLLIN),
    //                   socket.as_poll_item(zmq::POLLIN)];

    let items = &mut [zmq::PollItem::from_fd(pipefds.0),
                      socket.as_poll_item(zmq::POLLIN)];
    loop {
        let rc = zmq::poll(items, -1);
        match rc {
            Ok(v) => {
                assert!(v >= 0);
                if v == 0 {
                    continue;
                }
                if items[0].is_readable() {
                    let buffer = &mut [0; 1];
                    nix::unistd::read(pipefds.0, buffer).unwrap();
                    println!("W: interrupt received, killing server...");
                    break;
                }
                if items[1].is_readable() {
                    let buffer = &mut [0; 255];
                    let rc = socket.recv_into(buffer, zmq::DONTWAIT);
                    match rc {
                        Ok(_) => println!("W: recv"),
                        Err(e) => {
                            if e == zmq::Error::EAGAIN || e == zmq::Error::EINTR {
                                continue;
                            }
                            println!("recv: {}", e);
                            process::exit(1);
                        }
                    }
                }
            }
            Err(e) => {
                if e == zmq::Error::EINTR {
                    continue;
                }
                println!("zmq::poll: {}", e);
                process::exit(1);
            }
        }
    }
}
```

and I'm sure ```s_signal_handler``` has been called(when Ctrl+c).
